.github/workflows/wiki.yaml

Changes to documentation files on the main branch are synchronized into the
wiki for being more accessible.

GitHub: Workflow to sync wiki content

---

doxygen/src/pack_check.txt

The --diag-suppress options needs to be used for a list of error/warning messages.

Fixed packchk option

---

schema/PACK.xsd

We have QFP, QFN, SOP, but SON missing. Added.

Added SON chip package.

---

doxygen/pack.dxy
doxygen/src/General.txt
schema/PACK.xsd

This pull request contributes a change to an Open-CMSIS-Pack file schema.
Schema changes have a major impact on the tool ecosystem and need to be done carefully.
The Packs schema defines two types:`DeviceFeatureType` and `BoardFeatureType`. Both define two attributes `m` and `n`. These attributes were originally assigned a type of xsd:decimal, but this is too restrictive to encompass the range of values permitted for these attributes.
For example: Representation of display resolutions, e.g. `250 x 250`
CMSIS representation: `250.250`. This (originally) parses as a float which is `250.25`, which ends up reading as `250 x 25`
_checklist version 2021-11-10_
Minor change only, described in the section above.
No update required. The type is only described here, and is implicit in the existing …

Attribute types cannot be decimal

---

doxygen/src/General.txt
doxygen/src/components_schema.txt
schema/PACK.xsd

The original proposal was limited to adding 
`includeAsm`, `includeC`, `includeCpp` to `FileCategoryType` to be able to specifically control the include paths for assembler, c-compiler and c++ compiler command line.
REVIEW 1:
In this PR an `includeLd` is added to allow specifying include paths for the linker script preprocessing.
REVIEW 2:
In this PR the corresponding variants for FileCategoryType` `header` are added in addition to allow specifying the
- use case for the header file. A `headerC` file should be included in a C module, a `headerCpp` in a C++ module, etc.
- specifying the implicitly extracted include path to be restricted to Asm, C, C++ and linker command line.
We need to agree whether these additions are
a) relevant / meaningful
b) consistent
c) do not create unreasonable …

extend FileCategoryType (#28)

---

doxygen/src/components_schema.txt

Clarified that the attribute is only relevant for tools that attempt to select components automatically.
@fred-r please check whether this clarifies and resolves https://github.com/Open-CMSIS-Pack/devtools/issues/380#

Clarified isDefaultVariant

---

doxygen/src/generators_schema.txt

This variable expands to the absolute path of the generator input file
used to describe the current generator context
Add missing documentation for $B for boardName
Contributed by STMicroelectronics
Signed-off-by: Samuel HULTGREN <samuel.hultgren@st.com>
Fixes https://github.com/Open-CMSIS-Pack/devtools/issues/433

Document $G variable for <generator> variables

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/components_schema.txt
doxygen/src/pack_tutorial.txt
schema/PACK.xsd

projectpath is a folder path for a file. IDE can use it to construct file location folder in IDE project explorer view of workspace.

Add projectpath inside file element.

---

doxygen/src/devices_schema.txt
schema/PACK.xsd

Poor mans documentation of how numeric enums map to string values for `Dmpu` and friends.
While it logically makes sense that `0` is false and `1` is true, the order of table rows in the docs could indicate otherwise:
- [DfpuEnum starts with NO_FPU](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#DfpuEnum), reader might ask: does it mean `0` is `NO_FPU`
- [DmpuEnum starts with MPU](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#DmpuEnum), reader might ask: does it mean `0` is `MPU`?
From what I gather those numeric enums are deprecated. Is it worth listing those in doxygen tables anyway? I'd mark them deprecated. 
For now, I only reordered definitions in tables, so that `0` value matches first row.

Clarify numeric enums

---

doxygen/src/components_schema.txt

Clarify that components of a bundle inherit the version but can be redefined by each and every component.

clarify Cversion in bundles

---

schema/PACK.xsd

only the canonical UUID format is allowed

#191 restrict UUID

---

schema/PACK.xsd

Vendor names with '-' char should be allowed
For e.g 
M`DK-Packs`, `ARM-Packs`

Vendor name should allow '-' char as well

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/boards_schema.txt
doxygen/src/conditions_schema.txt
doxygen/src/devices_schema.txt
doxygen/src/parts_schema.txt
schema/PACK.xsd

Commit related to issue #182. This allows part specific filtering.

Add `Hvendor` and `Hname` as attributes of `accept`, `require` and `deny` elements

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/boards_schema.txt
doxygen/src/devices_schema.txt
schema/PACK.xsd

Aligned also \<book> element occurrence in "package/boards/board" table to XSD schema. Commit related to issue #220.

Specify that URL to a website is allowed in book element

---

schema/PACK.xsd

We would like to be able to describe startup component variant as:
`<vendor>::<Device>:Startup&C`
however currently Cclass, Cgroup, Cvariant are required to be at least 2 characters long.

lifting limitation to single character identifiers

---

doxygen/src/pdsc_format.txt

As we have introduced this tag late in the process, we must assume that non-tagged elements are true and you need to be actively stating that something is "false" = private.

Corrected assumption around "public"

---

doxygen/src/generators_schema.txt

Add attribute `mode` to generator arguments to allow specifying arguments that should only be passed to the generator if started in dry-run mode.
Implementation: https://github.com/Open-CMSIS-Pack/devtools/pull/1028
Related to issue #206
Contributed by STMicroelectronics

Add dry-run to generator command argument

---

doxygen/src/components_schema.txt
doxygen/src/conditions_schema.txt
doxygen/src/pack_tutorial.txt

Clarify that in conditions Cversion and Capiversion specified by minVersion only only resolve to true for compatible versions, meaning for the same major version value as specified in minVersion.
closing #273
closing #274

Clarify condition Cversion implicit range and bundle Cversion redefinition by components

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/examples_schema.txt
doxygen/src/pdsc_format.txt
schema/PACK.xsd

Also:
- Set PACK.xsd version to v1.7.35.
- Aligned documentation to xsd schema in the following points:
- "overview" attribute of the /package/description set to optional
- /package/examples/example/board set to 0..*
- /package/examples/example/project set to 1

Fix 'BOYAMICRO' vendor value in "DeviceVendorEnum"

---

doxygen/src/csolution_schema.txt
doxygen/src/pdsc_format.txt

- https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/310
- https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/311
- https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/309

Fixed typos in specification:

---

doxygen/src/generators_schema.txt

The `generators/generator/gpdsc` element has `type = xs:string` in the documentation while it has `type = GpdscFileType` in the Pack.xsd schema (with `GpdscFileType` that has an attribute `name = xs:string`).
In this PR I've aligned the description in the documentation to what is defined in the schema.

Align generators/generator/gpdsc description in doc to XSD schema

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/debug_description.txt
schema/PACK.xsd

This PR addresses #324 and provides a proposal for how to update the default `DebugPortStart` debug sequence to check and clear a DP's sticky error bits before starting the DP power-up sequence.
The changed sequence was tested with Keil MDK uVision and Arm Debugger, and with patched variants of real-world DFP PDSC files. Previously failing combinations work now. Previously working combinations didn't show regressions.
This PR updates both the docs revision history and the `Pack.xsd` revision history. Though I am not entirely sure if the latter was really necessary because this effectively is a docs-only change. Note the version gap from a previous docs-only change.

Github-324: Clear DP sticky error bits in 'DebugPortStart' sequence

---

doxygen/pack.dxy
doxygen/src/General.txt
schema/PACK.xsd

This aligns the schema with the documentation.

Added "mode" attribute to ExeGeneratorArgumentType

---

doxygen/pack.dxy
doxygen/src/General.txt
schema/PACK.xsd

Align with https://github.com/Open-CMSIS-Pack/devtools/pull/1887

[schema] Add `CLANG_TI` compiler

---

doxygen/src/components_schema.txt
doxygen/src/devices_schema.txt

This PR closes https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/340

Updates for #340

---

.github/workflows/gh-pages.yaml
.github/workflows/schema.yaml
doxygen/gen_doc.sh

This PR updates the GitHub Actions runner from ubuntu-20.04 to ubuntu-22.04.

Update GitHub Actions runner to ubuntu-22.04

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/devices_schema.txt
schema/PACK.xsd

Extend AP information with HPROT and SPROT [#2034](https://github.com/Open-CMSIS-Pack/devtools/issues/2034)

Add HPROT and SPROT attributes to accessportV1 and accessportV2 element

---

doxygen/pack.dxy
doxygen/src/General.txt
doxygen/src/devices_schema.txt
schema/PACK.xsd

remove datapatch types DP and Access_AP fixing #352

remove datapatch type attribute value `DP` and `ACCESS_AP`

---

doxygen/src/examples_schema.txt
schema/PACK.xsd

https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/355
This pull request contributes a change to an Open-CMSIS-Pack file schema.
Schema changes have a major impact on the tool ecosystem and need to be done carefully.
Updated ExampleProjectType to allow the "environment" element to have custom children and custom attributes
- Pack.xsd: updated ExampleProjectType to allow the existing "environment" element to have custom children and custom attributes
- examples_schema.txt: updated documentation accordingly (one more example code + updated table)
If yes is the reference to the pull request provided in the description above?

Updated ExampleProjectType to allow the "environment" element to have custom children and custom attributes
