Open-CMSIS-Pack/Open-CMSIS-Pack-Spec

- doxygen/src/components_schema.txt
Component description:  add hyperlinks to CclassType, CgroupType, Csubtype, VersionType
See https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack/issues/61
> [Doxygen] doc update

- doxygen/src/boards_schema.txt
- doxygen/src/pack_check.txt
- schema/PACK.xsd
This PR fixes the documentation and the PACk.xsd file as requested by issue #70.
> Fix for issue #70

- .github/workflows/schema.yaml
- test/pack_schema_version_history.py
- Checks that date/version are updated on every change
- Checks that same date/version is used all over the places, including
Doxygen documentation
> Add script to check consistency of PACK.xsd version history information

- doxygen/src/devices_schema.txt
- schema/PACK.xsd
> Added Jonzic

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/conditions_schema.txt
- doxygen/src/devices_schema.txt
- schema/PACK.xsd
- add 'Cortex-M85' to DcoreEnum
- add 'Dpacbti' attribute to Processor
- add 'Dpacbti' attribute to Condition
- add 'DpacbtiEnum'
> Enhance Pack schema for Cortex-M85:

- test/pack_schema_version_history.py
> Enhanced error messages of schema version check.

- doxygen/src/conditions_schema.txt
- doxygen/src/devices_schema.txt
Fixes Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#137
> DoxyGen: Fix links to processors.

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/apis_schema.txt
- doxygen/src/components_schema.txt
- doxygen/src/licenses_schema.txt
- doxygen/src/pdsc_format.txt
- schema/PACK.xsd
Add licenseSets to specification as requested in #24
> Add licenseSets

- .github/workflows/schema.yaml
- test/pack_schema_version_history.py
This should fix your issue @silviooliva.
> Schema version checker: Consider multiple commits in a pull-request

- doxygen/src/pack_check.txt
This corrects the level of the M377 message in the documentation.
> Fixing issue #139

- schema/PACK.xsd
Adding optional 'view' attribute to component element, allowing the predefined values "always", "never", "maskable".
> Schema changes for #112

- doxygen/src/conditions_schema.txt
Added 'Clang' to documentation of CompilerEnumType.
> #184 Added 'Clang'

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/components_schema.txt
- schema/PACK.xsd
Adding language and scope attributes to FileType and reverting #28.
> #186 add language and scope

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/boards_schema.txt
- schema/PACK.xsd
Signed-off-by: Silvio Lucio Oliva <silvio.oliva@st.com>
> Add bottom and large attributes to /package/boards/board/image

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/boards_schema.txt
- doxygen/src/devices_schema.txt
- schema/PACK.xsd
Signed-off-by: Silvio Lucio Oliva <silvio.oliva@st.com>
> Add 'NO_VENDOR:0' to DeviceVendorEnum

- schema/PACK.xsd
relates to https://github.com/Open-CMSIS-Pack/devtools/issues/600
> Restrict CIDs

- doxygen/pack.dxy
- doxygen/src/General.txt
- schema/PACK.xsd
> Add 'Renesas' to CompilerEnumType

- doxygen/src/generators_schema.txt
Synchronized with https://github.com/Open-CMSIS-Pack/devtools/pull/876
> WorkingDir clarified

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/boards_schema.txt
- doxygen/src/components_schema.txt
- doxygen/src/devices_schema.txt
- schema/PACK.xsd
> Add `environment` element at `board` and `component` level

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/parts_schema.txt
- schema/PACK.xsd
PR related to issue https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/246.
> Add "image" as child element of "part" element (#246)

- doxygen/src/generators_schema.txt
Contributed by STMicroelectronics
> Corrected broken end-tag in HTML table

- doxygen/pack.dxy
- doxygen/src/General.txt
- schema/PACK.xsd
> fix: update the schema for extension points

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/devices_schema.txt
- schema/PACK.xsd
> Add Cortex-M52

- doc/Glossary.md
Proposal to add concepts discussed in:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack/issues/33
> [Glossary] Proposing system description terminology

- README.md
Rules to submit PR on the spec https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/132
> Submit PR on spec

- doxygen/pack.dxy
- doxygen/src/apis_schema.txt
- doxygen/src/boards_schema.txt
- doxygen/src/clayers_schema.txt
- doxygen/src/components_schema.txt
- doxygen/src/conditions_schema.txt
- doxygen/src/devices_schema.txt
- doxygen/src/examples_schema.txt
- doxygen/src/generators_schema.txt
- doxygen/src/pdsc_format.txt
- schema/PACK.xsd
#293 feature NPU added
#292 category=header accepts public/private and select attribute
#291 pack description overview markdown file added
#275 brief description size max 256, recommended 128 
#58 attr=copy is deprecated
#56 clarified usage of Cclass/Cgroup/Csub/Cvariant/Cbundle in conditions
> Solves issues

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/pdsc_format.txt
- schema/PACK.xsd
> adding ECCN element

- doxygen/pack.dxy
- doxygen/src/General.txt
- doxygen/src/devices_schema.txt
- schema/PACK.xsd
This pull request contributes a change to an Open-CMSIS-Pack file schema.
Schema changes have a major impact on the tool ecosystem and need to be done carefully.
Added new device vendor 'HrdWyr'.
If yes is the reference to the pull request provided in the description above?
> Added HrdWyr
